version: '4'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=etwas
      - POSTGRES_DB=etwas
    ports:
      - "5432:5432"

volumes:
  postgres-data:
