name: Deploy to B590

on:
  pull_request:
    branches:
      - release
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./bot
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: |
          touch .env
          echo 'TZ=UTC' > .env
          echo ${{ secrets.DATABASE }} >> .env
          echo 'BOT_TOKEN="${{ secrets.BOT_TOKEN }}"' >> .env
          echo 'BOT_CLIENT_ID="${{ secrets.BOT_CLIENT_ID }}"' >> .env
          echo 'VOICEVOX_ENDPOINT="${{ secrets.VOICEVOX_ENDPOINT }}"' >> .env
          echo 'CNNAPI_ENDPOINT="${{ secrets.CNNAPI_ENDPOINT }}"' >> .env
          echo 'TWITCH_CLIENT_ID="${{ secrets.TWITCH_CLIENT_ID }}"' >> .env
          echo 'TWITCH_CLIENT_SECRET="${{ secrets.TWITCH_CLIENT_SECRET }}"' >> .env
          echo 'MC_API_ENDPOINT="${{ secrets.MC_API_ENDPOINT }}"' >> .env
          echo 'MC_API_TOKEN="${{ secrets.MC_API_TOKEN }}"' >> .env
          echo 'MC_CHAT_CHANNEL="${{ secrets.MC_CHAT_CHANNEL }}"' >> .env
      - name: Deploy Application Command
        run: npm run deploy-command
      - run: npx prisma migrate deploy
      - run: npx prisma generate
      - run: npm run build
      - run: pm2 startOrRestart ecosystem.config.js --env production --update-env
